#https://github.com/shaikahmadnawaz/react-docker
# Use an official Node runtime as a parent image
FROM node:16

WORKDIR /app
# Copy the package.json and package-lock.json to the working directory
COPY ./package*.json ./

# Install the dependencies
RUN npm install

# Copy the remaining application files to the working directory
COPY . .

# Build the application
RUN npm run build

# Expose port 8081 for the application
EXPOSE 8081

# Start the application
CMD [ "npm", "run", "start" ]