export const style = 'col-10 bg-dark text-light rounded border border-light row justify-content-start text-start p-0 m-0 align-baseline h-100 align-self-start';
export const app_style = 'bg-dark justify-content-center align-self-center align-content-center';
export const btn_success = 'btn btn-success border';
export const btn_danger = 'btn btn-danger border';
export const add_video_page = 'card p-1 m-3 bg-secondary border';
export const comment_page = 'd-flex row p-1 m-1 text-light';
export const comment_page_ul = 'pagination justify-content-center d-flex';
export const comment_page_li = 'page-link bg-secondary text-light'
export const comment_style = 'card col-4 text-light bg-dark border'
export const login_page_style = 'bg-dark text-light rounded border border-light justify-content-center align-self-center align-content-center'
export const login_group_style = 'button-group w-100 p-1'
export const login_btn_style = 'w-50 btn btn-success rounded border border-light'
export const login_register_style = 'w-50 btn btn-warning rounded border border-light'
export const main_page_style = 'bg-secondary text-light border w-100 h4 p-1 text-end'
export const main_page_section_style = 'd-flex p-0 m-0 col-12';
export const my_videos_page_style = 'card container-fluid p-1 m-0 row bg-dark text-light';
export const my_videos_header_style = 'card-header bg-secondary border';
export const my_videos_body_style = 'card-body row p-0 m-0 bg-secondary border';
export const my_videos_delete_style = 'btn btn-danger border';
export const registration_style = 'card row p-1 m-2 bg-secondary text-ligh border';
export const users_page_style = 'd-flex row p-0 m-0';
export const users_page_section_style = 'card col-6 bg-secondary border mt-2 d-block';
export const video_element_style = 'card col-6 bg-dark border text-light';
export const video_element_card_header_style = 'card-header text-wrap text-center';
export const video_element_card_body_style = 'card-body mh-75 w-100 row align-items-start p-1 m-0 d-block bg-secondary rounded border';
export const video_element_btn_style = 'btn btn-warning border';
export const menu_btn='btn text-light btn-dark border border-light';
