version: "1"
services:
  videoapp:
    image: mksrt/video-app:controller
    container_name: video_app_controller
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/VideoContentDataBase?createIfNotExists=true?useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update
    depends_on:
      - db
      - front
    ports:
      - "8080:8080"
    restart: always
  db:
    image: mysql
    container_name: video-sql-db
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=VideoContentDataBase
    ports:
      - "3306:3306"
    restart: always
  front:
    image: mksrt/video-app:front
    container_name: front
    ports:
      - "8081:8081"
